services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /home/marceloserver/deluge/config:/config
      - /home/marceloserver/Downloads/delugeMovies:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
    restart: unless-stopped
# sudo useradd -r -m -d /var/lib/deluge -s /usr/sbin/nologin -g deluge deluge
#
# sudo chown -R deluge:deluge /var/lib/deluge
#
#
