services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    #network_mode: "host"
    ports:
      - 8096:8096
    volumes:
      - /home/marcelo/docker/jellyfin/config:/config
      - /home/marcelo/docker/jellyfin/cache:/cache
      - type: bind
        source: /home/marcelo/Downloads
        target: /media
      - type: bind
        source: /home/marcelo/Downloads/torrentFiles
        target: /media2
        read_only: true
    restart: "unless-stopped"
    # Optional - alternative address used for autodiscovery
    environment:
      - PUID=1000
      - PGID=1000
      - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - "host.docker.internal:host-gateway"
